CREATE TABLE AIRPORT (
   AIRPORT_ID integer PRIMARY KEY,
   AIRPORT_NAME varchar(128) NOT NULL,
   ALTITUDE integer NOT NULL,
   CITY varchar(64) NOT NULL,
   COUNTRY varchar(64) NOT NULL,
   LATITUDE integer NOT NULL,
   LONGITUDE integer NOT NULL
);

CREATE TABLE AIRPLANE_AIRLINE (
   AIRPLANE_NO integer PRIMARY KEY,
	CAPACITY integer NOT NULL,
   AIRPLANE_NAME varchar(128) NOT NULL,
   AIRLINE_ID integer UNIQUE NOT NULL,
   AIRNINES_NAME varchar(128) NOT NULL,
   AIRLINES_ICAO varchar(128) NOT NULL,
   AIRLINES_IATA varchar(128) NOT NULL 
);
  
CREATE TABLE SEAT (
   SEAT_NO integer NOT NULL,
   AVAILABILITY boolean,
   LOCATION varchar(64) NOT NULL,
   CLASS varchar(64) NOT NULL,
   AIRPLANE_NO integer,
   PRIMARY KEY (AIRPLANE_NO, SEAT_NO),
   FOREIGN KEY (AIRPLANE_NO) REFERENCES AIRPLANE_AIRLINE (AIRPLANE_NO) ON DELETE CASCADE
);
 
CREATE TABLE STOP (
   STOP_ID integer PRIMARY KEY,
   ARRIVAL_TIME time NOT NULL,
   DEPART_TIME time NOT NULL,
   AIRPORT_ID integer NOT NULL,
   FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORT (AIRPORT_ID)
);
 
CREATE TABLE FLIGHT_TRIP (
   TRIP_ID integer PRIMARY KEY,
   NO_OF_TRAVELLERS integer NOT NULL,
   DEPARTURE_AIRPORT varchar(128) NOT NULL,   
   DEPART_TIME time NOT NULL,   
   ARRIVAL_AIRPORT varchar(128) NOT NULL,
   ARRIVAL_TIME time NOT NULL,   
   STOP_ID integer NOT NULL,
   DISTANCE integer NOT NULL,
   AIRPLANE_NO integer NOT NULL,
   FOREIGN KEY (STOP_ID) REFERENCES STOP (STOP_ID),
   FOREIGN KEY (AIRPLANE_NO) REFERENCES AIRPLANE_AIRLINE (AIRPLANE_NO)
);
 
CREATE TABLE FARE (
   TRIP_ID integer NOT NULL,
   TRANSACTION_ID integer NOT NULL,
   FINAL_AMOUNT integer NOT NULL,
   CURRENCY varchar(64) NOT NULL,
   PRIMARY KEY (TRIP_ID, TRANSACTION_ID),
   FOREIGN KEY (TRIP_ID) REFERENCES FLIGHT_TRIP (TRIP_ID) ON DELETE CASCADE
);
 
CREATE TABLE TRAVELLER (
   ID integer,
   FNAME varchar(128) NOT NULL,
   LNAME varchar(128) NOT NULL,
   PHONE varchar(128) NOT NULL,
   TRIP_ID integer NOT NULL,
   PRIMARY KEY (ID, TRIP_ID),
   FOREIGN KEY (TRIP_ID) REFERENCES FLIGHT_TRIP (TRIP_ID) ON DELETE CASCADE
);
 
CREATE TABLE USERS(
   EMAIL varchar(128) not null,
	USER_ID integer primary key,
   FNAME varchar(128),
   LNAME varchar(128),
   PHONE varchar(128),
   USER_TYPE varchar(128),
   TRIP_ID integer NOT NULL,
   FOREIGN KEY (TRIP_ID) REFERENCES FLIGHT_TRIP (TRIP_ID)
);
